---
title: Tantangan Minggu 1
format:
   pdf:
      geometry: 
         - top=30mm
         - bottom=30mm
   html:
      code-fold: true
      html-math-method: katex
   docx: default 
---

# WTnatangan Minggu 1

## UMUM

1.  (*Nilai 1 gram emas*) Petunjuk Penggunaan GitHub Untuk Kuliah EL-2007 Sinyal dan Sistem
    a.  Petunjuk Penggunaan GitHub Actions untuk Auto-Grading
    b.  Petunjuk Penggunaan GitHub Pages untuk Hosting Laporan
2.  (*Nilai 1 gram emas*) Petunjuk Penggunaan Quarto Untuk Laporan atau slides dalam bentuk docx, html, dan/atau pdf
3.  (*Nilai 1 gram emas*) Petunjuk Penggunaan Python beserta Jupyter Notebook untuk Pemrograman, beserta library numpy, scipy, matplotlib, dan sympy, serta mengintegrasikan ke dalam dokumen quarto
4.  (*Nilai 1 gram emas*) Petunjuk Penggunaan Visual Studio Code dan Obsidian untuk Editor qmd dan kode
5.  (*Nilai 1 gram emas*) Petunjuk Penggunaan Persaman latex, menggambar di Quarto menggunakan mermaid, graphviz dan plantUML
6.  (*Nilai 1 gram emas*) Petunjuk Penggunaan notebooklm dari Google untuk Membuat Notebook Interaktif

## Khusus

1.  (*Nilai 1 gram diamond Indonesia*) Jelaskan keluarga sinyal eksponensial.

2.  (*Nilai 1 gram diamond Indonesia*) Jelaskan keluarga sinyal sinusoidal.

3.  (*Nilai 4 gram platinum*) Jelaskan apa yang terjadi dengan transformasi dari fungsi real $f(t)$ menjadi $Af(b(t-T))$, serta dari $f[n]$ menjadi $Af(b(n-N))$, di mana $A$, $b$, dan $T$ adalah real dan $n$, $N$ integer.