project:
  type: book
  output-dir: .

book:
  title: "EL 2007 Sinyal dan Sistem"
  author: "Tim Sinyal dan Sistem"
  date: "8/2/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - 03_Hunter_Journals.md
    - summary.qmd
    - references.qmd
    - Lampiran-GITHUB-setting.md

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



