project:
  type: book
  output-dir: ../docs/03_Hunter_Journals/Nama_Lengkap_NIM

book:
  title: "Hunter_Journals"
  author: "Nama Lengkap  [NIM: 01234]"
  date: "8/2/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - journal_minggu_1.qmd

    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



